vim.cmd 'hi clear'
vim.g.colors_name = 'vitest'
vim.o.termguicolors = true

local hi = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Palette
local bg        = '#1c1b1a'
local bg_light  = '#252321'
local bg_sel    = '#332f2b'
local fg        = '#c8b9a6'
local fg_dim    = '#8a7e72'
local fg_dark   = '#665c52'
local salmon    = '#c97a6e'
local green     = '#80a665'
local amber     = '#c0a060'
local orange    = '#d49a6a'
local teal      = '#4c9a91'
local magenta   = '#b898b0'

-- Editor
hi('Normal',       { fg = fg, bg = bg })
hi('NormalFloat',  { fg = fg, bg = bg_light })
hi('FloatBorder',  { fg = fg_dim, bg = bg_light })
hi('Cursor',       { fg = bg, bg = fg })
hi('CursorLine',   { bg = bg_light })
hi('CursorLineNr', { fg = amber, bold = true })
hi('LineNr',       { fg = fg_dark })
hi('SignColumn',   { bg = bg })
hi('ColorColumn',  { bg = bg_light })
hi('Visual',       { bg = bg_sel })
hi('VisualNOS',    { bg = bg_sel })
hi('Search',       { fg = bg, bg = amber })
hi('IncSearch',    { fg = bg, bg = orange })
hi('CurSearch',    { fg = bg, bg = orange })
hi('Substitute',   { fg = bg, bg = salmon })
hi('MatchParen',   { fg = amber, bold = true, underline = true })
hi('Pmenu',        { fg = fg, bg = bg_light })
hi('PmenuSel',     { fg = fg, bg = bg_sel })
hi('PmenuSbar',    { bg = bg_light })
hi('PmenuThumb',   { bg = fg_dim })
hi('StatusLine',   { fg = fg, bg = bg_light })
hi('StatusLineNC', { fg = fg_dim, bg = bg_light })
hi('TabLine',      { fg = fg_dim, bg = bg_light })
hi('TabLineFill',  { bg = bg_light })
hi('TabLineSel',   { fg = fg, bg = bg })
hi('WinSeparator', { fg = fg_dark })
hi('Folded',       { fg = fg_dim, bg = bg_light })
hi('FoldColumn',   { fg = fg_dark, bg = bg })
hi('NonText',      { fg = fg_dark })
hi('SpecialKey',   { fg = fg_dark })
hi('Whitespace',   { fg = fg_dark })
hi('EndOfBuffer',  { fg = bg })
hi('Directory',    { fg = teal })
hi('Title',        { fg = amber, bold = true })
hi('ErrorMsg',     { fg = salmon })
hi('WarningMsg',   { fg = orange })
hi('ModeMsg',      { fg = fg, bold = true })
hi('MoreMsg',      { fg = green })
hi('Question',     { fg = teal })
hi('WildMenu',     { fg = bg, bg = amber })
hi('Conceal',      { fg = fg_dim })
hi('QuickFixLine',  { bg = bg_sel })
hi('WinBar',       { fg = fg, bg = bg })
hi('WinBarNC',     { fg = fg_dim, bg = bg })

-- Syntax
hi('Comment',      { fg = fg_dim, italic = true })
hi('Constant',     { fg = orange })
hi('String',       { fg = amber })
hi('Character',    { fg = amber })
hi('Number',       { fg = teal })
hi('Boolean',      { fg = orange })
hi('Float',        { fg = teal })
hi('Identifier',   { fg = fg })
hi('Function',     { fg = fg })
hi('Statement',    { fg = green })
hi('Conditional',  { fg = green })
hi('Repeat',       { fg = green })
hi('Label',        { fg = salmon })
hi('Operator',     { fg = fg_dim })
hi('Keyword',      { fg = green })
hi('Exception',    { fg = green })
hi('PreProc',      { fg = green })
hi('Include',      { fg = green })
hi('Define',       { fg = green })
hi('Macro',        { fg = green })
hi('PreCondit',    { fg = green })
hi('Type',         { fg = fg })
hi('StorageClass', { fg = green })
hi('Structure',    { fg = fg })
hi('Typedef',      { fg = fg })
hi('Special',      { fg = salmon })
hi('SpecialChar',  { fg = salmon })
hi('Tag',          { fg = green })
hi('Delimiter',    { fg = fg_dim })
hi('Debug',        { fg = salmon })
hi('Underlined',   { underline = true })
hi('Error',        { fg = salmon })
hi('Todo',         { fg = amber, bold = true })

-- Treesitter
hi('@variable',            { fg = fg })
hi('@variable.builtin',    { fg = salmon })
hi('@variable.parameter',  { fg = fg })
hi('@variable.member',     { fg = fg })
hi('@constant',            { fg = orange })
hi('@constant.builtin',    { fg = orange })
hi('@module',              { fg = fg })
hi('@string',              { fg = amber })
hi('@string.escape',       { fg = salmon })
hi('@string.regex',        { fg = salmon })
hi('@character',           { fg = amber })
hi('@number',              { fg = teal })
hi('@boolean',             { fg = orange })
hi('@float',               { fg = teal })
hi('@function',            { fg = fg })
hi('@function.builtin',    { fg = fg })
hi('@function.call',       { fg = fg })
hi('@function.method',     { fg = fg })
hi('@function.method.call', { fg = fg })
hi('@constructor',         { fg = fg })
hi('@keyword',             { fg = green })
hi('@keyword.function',    { fg = green })
hi('@keyword.return',      { fg = green })
hi('@keyword.operator',    { fg = green })
hi('@keyword.import',      { fg = green })
hi('@keyword.conditional', { fg = green })
hi('@keyword.repeat',      { fg = green })
hi('@keyword.exception',   { fg = green })
hi('@operator',            { fg = fg_dim })
hi('@punctuation.bracket',    { fg = fg_dim })
hi('@punctuation.delimiter',  { fg = fg_dim })
hi('@punctuation.special',    { fg = salmon })
hi('@type',                { fg = fg })
hi('@type.builtin',        { fg = fg })
hi('@type.qualifier',      { fg = green })
hi('@tag',                 { fg = green })
hi('@tag.attribute',       { fg = salmon })
hi('@tag.delimiter',       { fg = fg_dim })
hi('@property',            { fg = salmon })
hi('@attribute',           { fg = salmon })
hi('@label',               { fg = salmon })
hi('@comment',             { fg = fg_dim, italic = true })
hi('@markup.heading',      { fg = amber, bold = true })
hi('@markup.link',         { fg = teal, underline = true })
hi('@markup.raw',          { fg = amber })
hi('@markup.strong',       { fg = fg, bold = true })
hi('@markup.italic',       { fg = fg, italic = true })

-- LSP Semantic Tokens
hi('@lsp.type.namespace',  { fg = fg })
hi('@lsp.type.type',       { fg = fg })
hi('@lsp.type.class',      { fg = fg })
hi('@lsp.type.enum',       { fg = fg })
hi('@lsp.type.interface',  { fg = fg })
hi('@lsp.type.struct',     { fg = fg })
hi('@lsp.type.parameter',  { fg = fg })
hi('@lsp.type.variable',   { fg = fg })
hi('@lsp.type.property',   { fg = salmon })
hi('@lsp.type.function',   { fg = fg })
hi('@lsp.type.method',     { fg = fg })
hi('@lsp.type.macro',      { fg = green })
hi('@lsp.type.decorator',  { fg = salmon })
hi('@lsp.mod.deprecated',  { strikethrough = true })

-- Diagnostics
hi('DiagnosticError',          { fg = salmon })
hi('DiagnosticWarn',           { fg = orange })
hi('DiagnosticInfo',           { fg = teal })
hi('DiagnosticHint',           { fg = green })
hi('DiagnosticUnderlineError', { undercurl = true, sp = salmon })
hi('DiagnosticUnderlineWarn',  { undercurl = true, sp = orange })
hi('DiagnosticUnderlineInfo',  { undercurl = true, sp = teal })
hi('DiagnosticUnderlineHint',  { undercurl = true, sp = green })
hi('DiagnosticVirtualTextError', { fg = salmon, bg = '#2a1f1e' })
hi('DiagnosticVirtualTextWarn',  { fg = orange, bg = '#2a251e' })
hi('DiagnosticVirtualTextInfo',  { fg = teal, bg = '#1e252a' })
hi('DiagnosticVirtualTextHint',  { fg = green, bg = '#1e2a1e' })

-- Git signs
hi('GitSignsAdd',    { fg = green })
hi('GitSignsChange', { fg = amber })
hi('GitSignsDelete', { fg = salmon })
hi('DiffAdd',        { bg = '#1e2a1e' })
hi('DiffChange',     { bg = '#2a251e' })
hi('DiffDelete',     { bg = '#2a1f1e' })
hi('DiffText',       { bg = '#332f1e' })

-- Telescope
hi('TelescopeNormal',       { fg = fg, bg = bg_light })
hi('TelescopeBorder',       { fg = fg_dim, bg = bg_light })
hi('TelescopePromptNormal', { fg = fg, bg = bg_sel })
hi('TelescopePromptBorder', { fg = fg_dim, bg = bg_sel })
hi('TelescopePromptTitle',  { fg = bg, bg = amber })
hi('TelescopePreviewTitle', { fg = bg, bg = green })
hi('TelescopeResultsTitle', { fg = bg, bg = teal })
hi('TelescopeSelection',    { bg = bg_sel })
hi('TelescopeMatching',     { fg = amber, bold = true })

-- Neo-tree
hi('NeoTreeNormal',     { fg = fg, bg = bg })
hi('NeoTreeNormalNC',   { fg = fg, bg = bg })
hi('NeoTreeDirectoryName', { fg = teal })
hi('NeoTreeDirectoryIcon', { fg = teal })
hi('NeoTreeFileName',   { fg = fg })
hi('NeoTreeGitAdded',   { fg = green })
hi('NeoTreeGitModified', { fg = amber })
hi('NeoTreeGitDeleted', { fg = salmon })
hi('NeoTreeIndentMarker', { fg = fg_dark })

-- Which-key
hi('WhichKey',       { fg = amber })
hi('WhichKeyGroup',  { fg = teal })
hi('WhichKeyDesc',   { fg = fg })
hi('WhichKeySeparator', { fg = fg_dim })

-- Notify
hi('NotifyERRORBorder', { fg = salmon })
hi('NotifyWARNBorder',  { fg = orange })
hi('NotifyINFOBorder',  { fg = teal })
hi('NotifyDEBUGBorder', { fg = fg_dim })
hi('NotifyTRACEBorder', { fg = magenta })
hi('NotifyERRORTitle',  { fg = salmon })
hi('NotifyWARNTitle',   { fg = orange })
hi('NotifyINFOTitle',   { fg = teal })
hi('NotifyDEBUGTitle',  { fg = fg_dim })
hi('NotifyTRACETitle',  { fg = magenta })
hi('NotifyERRORIcon',   { fg = salmon })
hi('NotifyWARNIcon',    { fg = orange })
hi('NotifyINFOIcon',    { fg = teal })
hi('NotifyDEBUGIcon',   { fg = fg_dim })
hi('NotifyTRACEIcon',   { fg = magenta })

-- Indent blankline
hi('IblIndent', { fg = '#2a2725' })
hi('IblScope',  { fg = fg_dark })

-- Noice / Cmdline
hi('NoiceCmdlinePopup',       { fg = fg, bg = bg_light })
hi('NoiceCmdlinePopupBorder', { fg = fg_dim, bg = bg_light })
